# Generated by Django 5.0.6 on 2024-06-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='playlist.artist'),
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
